# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

author: Mario Measic-Gavran
baseurl: "" # the subpath of your site, e.g. /blog
description: > # this means to ignore newlines until "baseurl:"
  ...
email: mario.measic.gavran@gmail.com
future: true # Include posts with a date in the future
github_username: mmeasic
google_analytics: UA-151165575-1
highlighter: rouge
markdown: kramdown
permalink: /:categories/:title
plugins:
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-seo-tag
repository: mmeasic/mmeasic.github.io
social:
  name: Mario Measic-Gavran
  links:
    - https://instagram.com/mmeasic42
    - https://www.linkedin.com/in/mariomeasicgavran
    - https://github.com/mmeasic
title: Mario Measic-Gavran
instagram:
  username: mmeasic42
url: "https://mmeasic.github.io" # the base hostname & protocol for your site
include: ['_pages']
