# Site settings
title: Mario Measic
description: CV & Portfolio

# User settings
username: Mario Measic
user_title: Data Scientist/Engineer

# Build settings
remote_theme: mmeasic/jekyll-theme-minimal-resume