# Site settings
title: Mario Measic
description: CV & Portfolio

# User settings
username: Mario Measic
user_description: Problems are everywhere. Specifically, using variety of tools for data wrangling and mining. My professional experience and education revolve around moving and analyzing bits of information in order to create business value. Professionally, I have been working in the financial sector/industry, for banks and fintechs.
user_title: Data Scientist/Engineer

# Build settings
remote_theme: mmeasic/jekyll-theme-minimal-resume